#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Import ONE public upstream AIDL unchanged; emit its typed Java adapter.

The implementation sandbox cannot read the operator's source snapshots. Do not
invent a descriptor, transaction order or getter spelling to compensate. This
small preparation step is required before compilation, not run on the device.
It accepts only a two-method SafeMode contract with the supplied semantic shape;
any defeated assumption stops for source review. No raw Binder transactions or
reflective method invocation are generated.
"""
from pathlib import Path
import argparse
import hashlib
import re

HERE = Path(__file__).resolve().parent
JAVA = Path('src/dev/andrix/proof/webviewqualification/SafeModeContract.java')
IDENT = r'[A-Za-z_][A-Za-z_0-9]*'


def adapter(source):
    text = source.decode('utf-8')
    if not ('Copyright' in text and 'Chromium Authors' in text and 'BSD-style license' in text):
        raise ValueError('Expected upstream Chromium copyright/BSD notice, retained byte-for-byte')
    text = re.sub(r'/\*.*?\*/|//[^\n]*', '', text, flags=re.S)
    match = re.fullmatch(
        rf'\s*package\s+({IDENT}(?:\.{IDENT})*);\s*'
        r'(?:import\s+java\.util\.List;\s*)?'
        r'interface\s+ISafeModeService\s*\{(.*?)\}\s*', text, flags=re.S)
    if not match:
        raise ValueError('Unexpected AIDL declaration; review the exact upstream source')
    package, body = match.groups()
    methods = [part.strip() for part in body.split(';') if part.strip()]
    if len(methods) != 2 or not body.rstrip().endswith(';'):
        raise ValueError('Expected exactly two synchronous AIDL declarations')
    getter = None
    argument = None
    for method in methods:
        get = re.fullmatch(rf'long\s+({IDENT})\s*\(\s*\)', method)
        set_ = re.fullmatch(
            rf'void\s+setSafeMode\s*\(\s*in\s+(List\s*<\s*String\s*>|String\s*\[\s*\])'
            rf'\s+{IDENT}\s*\)', method)
        if get and getter is None and get[1].startswith('get'):
            getter = get[1]
        elif set_ and argument is None:
            argument = 'actions' if set_[1].startswith('List') else 'actions.toArray(new String[0])'
        else:
            raise ValueError('Unexpected method shape; do not guess or edit the upstream contract')
    if getter is None or argument is None:
        raise ValueError('Missing timestamp getter or setSafeMode')
    generated = f'''// Generated by prepare_contract.py from the unchanged public upstream AIDL.
// AIDL SHA-256: {hashlib.sha256(source).hexdigest()}
package dev.andrix.proof.webviewqualification;

import android.os.IBinder;
import android.os.RemoteException;
import java.util.List;
import {package}.ISafeModeService;

final class SafeModeContract {{
    static final String DESCRIPTOR = "{package}.ISafeModeService";
    private final ISafeModeService service;

    SafeModeContract(IBinder binder) {{
        service = ISafeModeService.Stub.asInterface(binder);
    }}

    long timestamp() throws RemoteException {{
        return service.{getter}();
    }}

    void setActions(List<String> actions) throws RemoteException {{
        service.setSafeMode({argument});
    }}
}}
'''
    return Path('aidl').joinpath(*package.split('.'), 'ISafeModeService.aidl'), generated.encode('utf-8')


def prepare(source, directory):
    aidl, generated = adapter(source)  # Validate fully before writing either source file.
    outputs = [(directory / aidl, source), (directory / JAVA, generated)]
    for path, content in outputs:
        if path.exists() and path.read_bytes() != content:
            raise ValueError(f'Refusing to replace a different existing input: {path}')
    for path, content in outputs:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)
    return aidl


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('upstream_aidl', type=Path,
                        help='exact public ISafeModeService.aidl from the frozen source snapshot')
    args = parser.parse_args()
    source = args.upstream_aidl.read_bytes()
    aidl = prepare(source, HERE)
    print(f'Imported unchanged {aidl}; SHA-256 {hashlib.sha256(source).hexdigest()}')
    print('Review against SafeModeService and the frozen DEX before build/run; no runtime test was performed.')


if __name__ == '__main__':
    main()
