// Generated by prepare_contract.py from the unchanged public upstream AIDL.
// AIDL SHA-256: 881975244f5e77d7f3184484b78cd2f4c5cbe2931e69887c2172e16c68c66abc
package dev.andrix.proof.webviewqualification;

import android.os.IBinder;
import android.os.RemoteException;
import java.util.List;
import org.chromium.android_webview.common.services.ISafeModeService;

final class SafeModeContract {
    static final String DESCRIPTOR = "org.chromium.android_webview.common.services.ISafeModeService";
    private final ISafeModeService service;

    SafeModeContract(IBinder binder) {
        service = ISafeModeService.Stub.asInterface(binder);
    }

    long timestamp() throws RemoteException {
        return service.getSafeModeActivationTimestamp();
    }

    void setActions(List<String> actions) throws RemoteException {
        service.setSafeMode(actions);
    }
}
