#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Reads a caiman flash-all.sh against the official GrapheneOS script (rules 4, 5 and 6).

GrapheneOS writes the script in two forms, and this reader supports both:

- legacy: device/common/generate-factory-images-common.sh, sourced by
  script/generate-release.sh with caiman's settings (DISABLE_UART, DISABLE_FIPS,
  DISABLE_DPM, AVB_PKMD, BOOTLOADER and RADIO from android-info.txt, lowercased). The
  whole expected text is fixed by the bootloader version, the baseband version and the
  build number, so the script must equal it byte for byte.
- optimized: what "fastboot -S 0xf900000 optimize-factory-image" writes into the published
  install zip, through FlashCapturer in system/core/fastboot/fastboot.cpp. Everything up
  to "fastboot snapshot-update cancel" is fixed and must be equal byte for byte. The OS
  images that follow come from the image zip's fastboot-info.txt, so they are read as a
  fixed list of static images, the wipe erases and a numbered run of super splits.

The optimized OS image list and wipe erases are fixed in this file. They are NOT yet
confirmed by any real install zip; DEFAULT_OS_IMAGES explains where they come from. No
option changes them at run time. A script that differs is refused until a reviewed change
to this file records what the real one does.

flash-all.bat and script.txt are not read.
"""
import argparse
from dataclasses import dataclass
from pathlib import Path
import re
import shlex
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))
import caiman  # noqa: E402
from caiman import Refusal, refuse  # noqa: E402

FORMS = ('legacy', 'optimized')
MAX_SCRIPT = 1 << 20

# The static OS partitions of caiman are its AB_OTA_PARTITIONS in adevtool's generated
# BoardConfig.mk, without the firmware inside the bootloader and radio images and without
# the dynamic partitions in super. Every one is also in FlashCapturer's variable table.
# The order is the order of AOSP's generated fastboot-info.txt as recalled, not as read:
# adevtool sets no TARGET_BOARD_FASTBOOT_INFO_FILE, and build/make was not available.
DEFAULT_OS_IMAGES = ('boot', 'init_boot', 'dtbo', 'vendor_kernel_boot', 'pvmfw', 'vendor_boot',
                     'vbmeta')
# fastboot-info.txt's "if-wipe erase" lines, which FlashCapturer records. Also unconfirmed.
DEFAULT_WIPE = ('userdata', 'metadata')
STATIC_OS = frozenset(DEFAULT_OS_IMAGES) | {'vbmeta_system', 'vbmeta_vendor'}
MAX_DOWNLOAD_SIZE = '0xf900000'   # script/generate-release.sh for caiman

PROLOG = '''\
#!/bin/sh

#    SSSSSSSSSSSSSSS  TTTTTTTTTTTTTTTTTTTTTTT      OOOOOOOOO      PPPPPPPPPPPPPPPPP
#  SS:::::::::::::::S T:::::::::::::::::::::T    OO:::::::::OO    P::::::::::::::::P
# S:::::SSSSSS::::::S T:::::::::::::::::::::T  OO:::::::::::::OO  P::::::PPPPPP:::::P
# S:::::S     SSSSSSS T:::::TT:::::::TT:::::T O:::::::OOO:::::::O PP:::::P     P:::::P
# S:::::S             TTTTTT  T:::::T  TTTTTT O::::::O   O::::::O   P::::P     P:::::P
# S:::::S                     T:::::T         O:::::O     O:::::O   P::::P     P:::::P
#  S::::SSSS                  T:::::T         O:::::O     O:::::O   P::::PPPPPP:::::P
#   SS::::::SSSSS             T:::::T         O:::::O     O:::::O   P:::::::::::::PP
#     SSS::::::::SS           T:::::T         O:::::O     O:::::O   P::::PPPPPPPPP
#        SSSSSS::::S          T:::::T         O:::::O     O:::::O   P::::P
#             S:::::S         T:::::T         O:::::O     O:::::O   P::::P
#             S:::::S         T:::::T         O::::::O   O::::::O   P::::P
# SSSSSSS     S:::::S       TT:::::::TT       O:::::::OOO:::::::O PP::::::PP
# S::::::SSSSSS:::::S       T:::::::::T        OO:::::::::::::OO  P::::::::P
# S:::::::::::::::SS        T:::::::::T          OO:::::::::OO    P::::::::P
#  SSSSSSSSSSSSSSS          TTTTTTTTTTT            OOOOOOOOO      PPPPPPPPPP
#
# DO NOT EDIT THIS FILE. THE OFFICIAL GRAPHENEOS INSTALL GUIDE WILL NEVER INSTRUCT YOU
# TO EDIT THIS FILE. IF YOU ARE FOLLOWING A 3RD PARTY GUIDE YOU SHOULD STOP IMMEDIATELY
# AND START OVER AND FOLLOW THE OFFICIAL INSTALLATION PROCESS ON THE OFFICIAL WEBSITE.
# USING THE WEB INSTALLER IS STRONGLY RECOMMENDED https://grapheneos.org/install/web
# THE CLI INSTALLATION PROCESS SHOULD ONLY BE USED BY USERS WITH SPECIFIC NEEDS.

# Copyright 2012 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if ! command -v fastboot > /dev/null; then
  echo "fastboot not found"
  echo "Download the latest version at https://developer.android.com/studio/releases/platform-tools.html and add it to the shell PATH"
  exit 1
fi

set -e

FASTBOOT_VERSION_STR=$(fastboot --version | grep "fastboot version " | cut -c18-23)
FASTBOOT_VERSION_NUM=$(echo $FASTBOOT_VERSION_STR | tr -d .)
if ! [ $FASTBOOT_VERSION_NUM -ge 3501 ]; then
  echo "fastboot version ($FASTBOOT_VERSION_STR) is older than the minimum supported version (35.0.1)."
  echo "Download the latest version at https://developer.android.com/studio/releases/platform-tools.html and add it to the shell PATH"
  exit 1
fi
'''


@dataclass(frozen=True)
class Expectation:
    bootloader: str                 # version-bootloader of the release's android-info.txt
    baseband: str                   # version-baseband of the release's android-info.txt
    build: object = None            # release number, needed by the legacy form
    wipe = True                     # rule 6: both official forms always wipe data
    max_download_size: str = MAX_DOWNLOAD_SIZE
    os_images = DEFAULT_OS_IMAGES          # fixed: unconfirmed until a real zip is read
    wipe_partitions = DEFAULT_WIPE

    @property
    def bootloader_file(self):
        return f'bootloader-{caiman.DEVICE}-{self.bootloader.lower()}.img'

    @property
    def radio_file(self):
        return f'radio-{caiman.DEVICE}-{self.baseband.lower()}.img'


def _check_var(name, value, message):
    short = name.replace('-', '').replace('_', '')
    return [f'{short}=$(fastboot getvar {name} 2>&1 | grep "{name}:" | cut -d \' \' -f 2)',
            f'if ! [ ${short} = "{value}" ]; then', f'  echo {message}${short}', '  exit 1', 'fi']


def _bootloader_lines(expect):
    flash = f'fastboot flash --slot=other bootloader {expect.bootloader_file}'
    return [flash, 'fastboot --set-active=other', 'fastboot reboot-bootloader', 'sleep 5',
            flash, 'fastboot --set-active=other', 'fastboot reboot-bootloader', 'sleep 5']


def _middle_lines(expect):
    return [f'fastboot flash radio {expect.radio_file}', 'fastboot reboot-bootloader', 'sleep 5',
            'fastboot erase avb_custom_key', 'fastboot flash avb_custom_key avb_pkmd.bin',
            'fastboot oem uart disable', 'fastboot erase fips', 'fastboot erase dpm_a',
            'fastboot erase dpm_b']


def legacy_lines(expect):
    """The whole script generate-factory-images-common.sh writes for caiman."""
    if expect.build is None:
        refuse('the legacy form names the image zip by build number, so the build is needed')
    build = caiman.parse_release(str(expect.build), what='build number').number
    wipe = '-w ' if expect.wipe else ''
    return (PROLOG.split('\n')[:-1] + [
        '', '# PROLOG_END', '# The above line is used by FlashCapturer in fastboot', '',
        'product=$(fastboot getvar product 2>&1 | grep "product:" | cut -d \' \' -f 2)',
        f'if ! [ $product = {caiman.DEVICE} ]; then',
        '  echo "You\'re attempting to flash the wrong factory images. This would likely brick '
        'your device."',
        '  echo',
        f'  echo "These factory images are for {caiman.DEVICE} and the detected device is '
        '$product."',
        '  exit 1', 'fi', ''] + _bootloader_lines(expect) + _middle_lines(expect) + [
        f'fastboot {wipe}--skip-reboot update image-{caiman.DEVICE}-{build}.zip',
        'fastboot reboot-bootloader', 'sleep 5'])


def optimized_head(expect):
    """FlashCapturer's fixed part, up to and including the snapshot cancel."""
    return (PROLOG.split('\n')[:-1] + ['', 'echo Available devices:', 'fastboot devices -l']
            + _check_var('product', caiman.DEVICE,
                         f'Error: this factory image is for {caiman.DEVICE}, but the name of '
                         'connected device is ')
            + _check_var('slot-count', '2', 'Error: unexpected value of slot-count variable: '
                         'expected 2, got ')
            + _bootloader_lines(expect)
            + ['# size of partition splits depends on this value']
            + _check_var('max-download-size', expect.max_download_size,
                         'Error: unexpected value of max-download-size variable: expected '
                         f'{expect.max_download_size}, got ')
            + ['# layout of the super partition depends on the current slot, which is hardcoded '
               'to slot A', 'fastboot --set-active=a']
            + _check_var('current-slot', 'a', 'Error: unexpected value of current-slot variable: '
                         'expected a, got ')
            + _middle_lines(expect)
            + ['# this command only checks android-info.txt requirements, it does not perform an '
               'update', 'fastboot --disable-super-optimization --skip-reboot update android-info.zip',
               'fastboot snapshot-update cancel'])


def optimized_os_lines(expect, splits):
    lines = [f'fastboot flash {name} {name}.img' for name in expect.os_images]
    if expect.wipe:
        lines += [f'fastboot erase {name}' for name in expect.wipe_partitions]
    for number in range(1, splits + 1):
        lines += [f'echo Flashing super, {number}/{splits}',
                  f'fastboot flash super super_{number}.img']
    return lines


# fastboot's options at GrapheneOS 2026100600 (FastBootTool::Main). getopt_long accepts any
# unambiguous prefix of a long option, so "--forc" is "--force".
LONG_OPTIONS = {'base': True, 'cmdline': True, 'disable-verification': False,
                'disable-verity': False, 'disable-super-optimization': False,
                'exclude-dynamic-partitions': False, 'disable-fastboot-info': False,
                'force': False, 'fs-options': True, 'header-version': True, 'help': False,
                'kernel-offset': True, 'os-patch-level': True, 'os-version': True,
                'page-size': True, 'ramdisk-offset': True, 'set-active': None,
                'skip-reboot': False, 'skip-secondary': False, 'slot': True,
                'tags-offset': True, 'dtb': True, 'dtb-offset': True, 'unbuffered': False,
                'verbose': False, 'version': False}
SHORT_OPTIONS = {'a': 'set-active', 'h': 'help', 'l': 'long-listing', 's': 'serial',
                 'S': 'sparse-limit', 'v': 'verbose', 'w': 'wipe'}
INDIRECT = {'eval', 'exec', 'sh', 'bash', 'dash', 'env', 'command', 'xargs', 'sudo', 'doas',
            'source', '.', 'su', 'nohup', 'time', 'timeout', 'busybox'}
SHELL_WORDS = {'{', '}', '!', 'if', 'then', 'else', 'elif', 'fi', 'do', 'done', 'while', 'until'}
LOCKING = {('flashing', 'lock'), ('flashing', 'lock_critical'), ('oem', 'lock')}
UNLOCKING = {('flashing', 'unlock'), ('flashing', 'unlock_critical'), ('oem', 'unlock')}


def _long(name):
    if name in LONG_OPTIONS:
        return name
    matches = [option for option in LONG_OPTIONS if option.startswith(name)]
    return matches[0] if len(matches) == 1 and name else None


def parse_invocation(args):
    """Splits fastboot's arguments into options and positional words, as getopt does."""
    options, words, problems = [], [], []
    index = 0
    while index < len(args):
        arg = args[index]
        if arg == '--':
            words.extend(args[index + 1:])
            break
        if arg.startswith('--'):
            name, has_value, value = arg[2:].partition('=')
            full = _long(name)
            if full is None:
                problems.append(f'unknown or ambiguous option {arg}')
            elif LONG_OPTIONS[full] and not has_value:
                index += 1
                value = args[index] if index < len(args) else ''
                has_value = True
            options.append((full or arg, value if has_value else None))
        elif arg.startswith('-') and arg != '-':
            for position, letter in enumerate(arg[1:], 1):
                name = SHORT_OPTIONS.get(letter)
                if name is None:
                    problems.append(f'unknown option -{letter}')
                    break
                if letter == 'a':
                    options.append((name, arg[position + 1:] or None))
                    break
                if letter in 'sS':
                    value = arg[position + 1:]
                    if not value:
                        index += 1
                        value = args[index] if index < len(args) else ''
                    options.append((name, value))
                    break
                options.append((name, None))
        else:
            words.append(arg)
        index += 1
    return options, words, problems


def classify(args, form, expect):
    """Reasons why one fastboot invocation outside the official lines is forbidden."""
    options, words, problems = parse_invocation(args)
    reasons = list(problems)
    names = {name for name, _ in options}
    command = tuple(words[:2])
    if 'force' in names:
        reasons.append('--force (rule 4)')
    for name, value in options:
        if name == 'set-active':
            reasons.append(f'--set-active{"=" + value if value else ""} outside the official '
                           'bootloader sequence (rule 4)')
        elif name == 'slot':
            reasons.append(f'--slot={value} outside the official bootloader sequence (rule 4)')
        elif name in ('disable-verity', 'disable-verification'):
            reasons.append(f'--{name} switches verified boot checks off')
        elif name not in ('wipe', 'skip-reboot', 'disable-super-optimization', 'force'):
            reasons.append(f'option {name} is not used by the official script')
    if not words:
        if not names & {'set-active'} and not reasons:
            reasons.append('fastboot without a command is not in the official script')
        return reasons
    verb = words[0]
    if command in LOCKING:
        reasons.append(f'"{" ".join(command)}" locks the bootloader (rule 2)')
    elif command in UNLOCKING:
        reasons.append(f'"{" ".join(command)}" unlocks; only stage 7 unlocks, never a flash script')
    elif verb == 'set_active':
        reasons.append('set_active (rule 4)')
    elif verb.startswith('format'):
        reasons.append(f'{verb} {" ".join(words[1:])} formats a partition (rule 6)')
    elif verb == 'erase':
        reasons.append(f'erases {" ".join(words[1:]) or "nothing named"} (rule 6)')
    elif verb in ('flash', 'flash:raw'):
        reasons.append(f'{verb} {" ".join(words[1:])} writes a partition the official script does '
                       'not write there (rule 6)')
    elif verb == 'update':
        reasons.append(f'update {" ".join(words[1:])} is not the official update (rules 4 and 6)')
    elif verb == 'oem':
        reasons.append(f'oem {" ".join(words[1:])} is not in the official script')
    elif verb in ('flashall', 'boot', 'wipe-super', 'create-logical-partition',
                  'delete-logical-partition', 'resize-logical-partition', 'gsi', 'stage',
                  'get_staged', 'fetch', 'continue', 'signature', 'download', 'upload',
                  'snapshot-update', 'flashing', 'reboot', 'reboot-recovery', 'reboot-fastboot',
                  'reboot-bootloader', 'getvar', 'devices', 'shutdown'):
        reasons.append(f'"{" ".join(words)}" is not in the official script at this place (rule 4)')
    else:
        reasons.append(f'unknown fastboot command {verb!r}')
    return reasons


def _simple_commands(line):
    lexer = shlex.shlex(line, posix=True, punctuation_chars=True)
    lexer.whitespace_split = True
    lexer.commenters = '#'
    words = list(lexer)
    command = []
    for word in words + [';']:
        if word and set(word) <= set(';&|()<>'):
            if command:
                yield command
            command = []
        else:
            command.append(word)


def scan(lines, official, form, expect):
    """Findings for every line that is not one of the official lines of this form."""
    findings = []
    for number, line in enumerate(lines, 1):
        if line in official or line.strip() == '' or line.lstrip().startswith('#'):
            continue
        if '`' in line:
            findings.append(f'line {number}: backquote command substitution is not in the '
                            'official script')
        try:
            commands = list(_simple_commands(line))
        except ValueError as error:
            findings.append(f'line {number}: unparsable shell line ({error})')
            continue
        for words in commands:
            while words and (words[0] in SHELL_WORDS
                             or re.fullmatch(r'[A-Za-z_][A-Za-z0-9_]*=.*', words[0])):
                if 'fastboot' in words[0] and words[0] not in SHELL_WORDS:
                    findings.append(f'line {number}: stores fastboot in a variable')
                words = words[1:]
            if not words:
                continue
            program = words[0].rsplit('/', 1)[-1]
            if program.startswith('$'):
                findings.append(f'line {number}: runs a command through a variable')
            elif program == 'fastboot':
                for reason in classify(words[1:], form, expect):
                    findings.append(f'line {number}: {reason}')
            elif program in INDIRECT:
                findings.append(f'line {number}: {program} can run commands indirectly')
            elif 'fastboot' in ' '.join(words):
                findings.append(f'line {number}: fastboot used in a way the official script '
                                'does not use it')
    return findings


def _first_difference(found, wanted, offset=0):
    for index, (have, want) in enumerate(zip(found, wanted)):
        if have != want:
            where = f'line {offset + index + 1}'
            if have in wanted:
                return (f'{where}: found {have!r}, which belongs at line '
                        f'{offset + wanted.index(have) + 1}; expected {want!r} (order differs)')
            return f'{where}: expected {want!r}, found {have!r}'
    if len(found) < len(wanted):
        return f'line {offset + len(found) + 1}: the script ends early; expected {wanted[len(found)]!r}'
    if len(found) > len(wanted):
        return f'line {offset + len(wanted) + 1}: unexpected extra line {found[len(wanted)]!r}'
    return None


def split_script(data):
    if not isinstance(data, bytes) or len(data) > MAX_SCRIPT:
        refuse('the script is not bytes or is larger than 1 MiB')
    try:
        text = data.decode('ascii')
    except UnicodeDecodeError:
        refuse('the script is not ASCII')
    if '\r' in text or '\0' in text or '\t' in text:
        refuse('the script contains carriage returns, tabs or NUL bytes')
    if not text.endswith('\n'):
        refuse('the script does not end with a newline')
    return text[:-1].split('\n')


def _super_splits(lines, start):
    """The number of super splits in a well formed run, or None."""
    count = (len(lines) - start) // 2
    if count < 1 or start + 2 * count != len(lines):
        return None
    for number in range(1, count + 1):
        if (lines[start + 2 * number - 2] != f'echo Flashing super, {number}/{count}'
                or lines[start + 2 * number - 1] != f'fastboot flash super super_{number}.img'):
            return None
    return count


def read(data, expect, form=None):
    """Reads one script. Returns a report; the verdict is PASS only if nothing differs."""
    lines = split_script(data)
    if form is None:
        form = ('optimized' if 'echo Available devices:' in lines
                else 'legacy' if '# PROLOG_END' in lines else None)
        if form is None:
            refuse('neither the legacy nor the optimized form: no "# PROLOG_END" line and no '
                   '"echo Available devices:" line')
    if form not in FORMS:
        refuse(f'unknown form {form!r}')
    report = {'form': form, 'files': [expect.bootloader_file, expect.radio_file, 'avb_pkmd.bin']}
    if form == 'legacy':
        wanted = legacy_lines(expect)
        difference = _first_difference(lines, wanted)
        official = set(wanted)
        report['files'].append(f'image-{caiman.DEVICE}-{expect.build}.zip')
    else:
        head = optimized_head(expect)
        difference = _first_difference(lines[:len(head)], head)
        start = len(head)
        fixed = optimized_os_lines(expect, 0)
        splits = None
        if difference is None:
            difference = _first_difference(lines[start:start + len(fixed)], fixed, start)
            if difference is None and len(lines) < start + len(fixed) + 2:
                difference = f'line {len(lines) + 1}: the script ends before any super split'
        if difference is None:
            splits = _super_splits(lines, start + len(fixed))
            if splits is None:
                wanted_tail = optimized_os_lines(expect, max(1, (len(lines) - start - len(fixed)) // 2))
                difference = (_first_difference(lines[start:], wanted_tail, start)
                              or 'the super splits are not one numbered run')
        official = set(head) | set(fixed)
        official |= {line for line in lines if re.fullmatch(
            r'echo Flashing super, [1-9][0-9]{0,2}/[1-9][0-9]{0,2}|'
            r'fastboot flash super super_[1-9][0-9]{0,2}\.img', line)}
        report['super_splits'] = splits
        report['os_images'] = list(expect.os_images)
        report['files'] += ['android-info.zip'] + [f'{name}.img' for name in expect.os_images]
        report['files'] += [f'super_{number}.img' for number in range(1, (splits or 0) + 1)]
        report['unconfirmed'] = ('the OS image list, its order and the wipe erases are an '
                                 'expectation not yet confirmed by a real install zip')
    findings = scan(lines, official, form, expect)
    reasons = findings + ([difference] if difference else [])
    report['verdict'] = 'REFUSE' if reasons else 'PASS'
    report['reasons'] = reasons
    report['commands'] = [line for line in lines if line.startswith('fastboot ')]
    return report


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    parser.add_argument('script', help='the flash-all.sh to read')
    parser.add_argument('--android-info', required=True,
                        help="the release's android-info.txt, for the firmware file names")
    parser.add_argument('--build', help='release number; needed by the legacy form')
    parser.add_argument('--form', choices=FORMS, help='default: detect')
    args = parser.parse_args(argv)
    try:
        info = caiman.parse_android_info(Path(args.android_info).read_bytes())
        expect = Expectation(info.bootloader, info.baseband, args.build)
        report = read(Path(args.script).read_bytes(), expect, args.form)
    except (Refusal, OSError) as error:
        sys.stdout.write(caiman.dump({'verdict': 'REFUSE', 'reasons': [str(error)]}))
        return 1
    sys.stdout.write(caiman.dump(report))
    return 0 if report['verdict'] == 'PASS' else 1


if __name__ == '__main__':
    sys.exit(main())
